import type { Metadata } from 'next'
import '@/shared/styles/globals.css'
import { Nunito } from 'next/font/google'
import Head from 'next/head'
import QueryProviders from '@/providers/QueryProvider'

const nunito = Nunito({
  variable: '--font-nunito-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Abz Users',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${nunito.variable}`}>
      <Head>
        <link
          rel="preconnect"
          href="https://frontend-test-assignment-api.abz.agency"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/assets/title.webp"
          as="image"
          fetchPriority="high"
        />
      </Head>
      <body>
        <main>
          <QueryProviders>{children}</QueryProviders>
        </main>
      </body>
    </html>
  )
}
