import type { Metadata } from 'next'
import '@/shared/styles/globals.css'
import { Nunito } from 'next/font/google'

const nunito = Nunito({
  variable: '--font-nunito-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Abz Users',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${nunito.variable}`}>
      <body>
        <main>{children}</main>
      </body>
    </html>
  )
}
